// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spirits.proto

/*
Package gogrpc is a generated protocol buffer package.

It is generated from these files:
	spirits.proto

It has these top-level messages:
	Spirit
	SpiritCreationRequest
	SpiritUpdateRequest
	SpiritDeleteRequest
	SpiritSearchRequest
	SpiritCreationResponse
	SpiritUpdateResponse
	SpiritDeleteResponse
	SpiritSearchResponse
*/
package gogrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Spirit_SpiritType int32

const (
	Spirit_TypeRhum      Spirit_SpiritType = 0
	Spirit_TypeWine      Spirit_SpiritType = 1
	Spirit_TypeWhisky    Spirit_SpiritType = 2
	Spirit_TypeChampagne Spirit_SpiritType = 3
	Spirit_TypeGin       Spirit_SpiritType = 4
	Spirit_TypeBier      Spirit_SpiritType = 5
)

var Spirit_SpiritType_name = map[int32]string{
	0: "TypeRhum",
	1: "TypeWine",
	2: "TypeWhisky",
	3: "TypeChampagne",
	4: "TypeGin",
	5: "TypeBier",
}
var Spirit_SpiritType_value = map[string]int32{
	"TypeRhum":      0,
	"TypeWine":      1,
	"TypeWhisky":    2,
	"TypeChampagne": 3,
	"TypeGin":       4,
	"TypeBier":      5,
}

func (x Spirit_SpiritType) String() string {
	return proto.EnumName(Spirit_SpiritType_name, int32(x))
}
func (Spirit_SpiritType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Spirit struct {
	Id          string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Distiller   string            `protobuf:"bytes,3,opt,name=Distiller" json:"Distiller,omitempty"`
	Bottler     string            `protobuf:"bytes,4,opt,name=Bottler" json:"Bottler,omitempty"`
	Country     string            `protobuf:"bytes,5,opt,name=Country" json:"Country,omitempty"`
	Region      string            `protobuf:"bytes,6,opt,name=Region" json:"Region,omitempty"`
	Composition string            `protobuf:"bytes,7,opt,name=Composition" json:"Composition,omitempty"`
	Type        Spirit_SpiritType `protobuf:"varint,8,opt,name=type,enum=gogrpc.Spirit_SpiritType" json:"type,omitempty"`
	Age         int32             `protobuf:"varint,9,opt,name=Age" json:"Age,omitempty"`
	// google.protobuf.Timestamp BottlingDate = 10;
	BottlingDate int64   `protobuf:"varint,10,opt,name=BottlingDate" json:"BottlingDate,omitempty"`
	Score        float32 `protobuf:"fixed32,11,opt,name=Score" json:"Score,omitempty"`
	Comment      string  `protobuf:"bytes,12,opt,name=Comment" json:"Comment,omitempty"`
}

func (m *Spirit) Reset()                    { *m = Spirit{} }
func (m *Spirit) String() string            { return proto.CompactTextString(m) }
func (*Spirit) ProtoMessage()               {}
func (*Spirit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Spirit) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Spirit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Spirit) GetDistiller() string {
	if m != nil {
		return m.Distiller
	}
	return ""
}

func (m *Spirit) GetBottler() string {
	if m != nil {
		return m.Bottler
	}
	return ""
}

func (m *Spirit) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Spirit) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Spirit) GetComposition() string {
	if m != nil {
		return m.Composition
	}
	return ""
}

func (m *Spirit) GetType() Spirit_SpiritType {
	if m != nil {
		return m.Type
	}
	return Spirit_TypeRhum
}

func (m *Spirit) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Spirit) GetBottlingDate() int64 {
	if m != nil {
		return m.BottlingDate
	}
	return 0
}

func (m *Spirit) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Spirit) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type SpiritCreationRequest struct {
	Spirit *Spirit `protobuf:"bytes,1,opt,name=spirit" json:"spirit,omitempty"`
}

func (m *SpiritCreationRequest) Reset()                    { *m = SpiritCreationRequest{} }
func (m *SpiritCreationRequest) String() string            { return proto.CompactTextString(m) }
func (*SpiritCreationRequest) ProtoMessage()               {}
func (*SpiritCreationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SpiritCreationRequest) GetSpirit() *Spirit {
	if m != nil {
		return m.Spirit
	}
	return nil
}

type SpiritUpdateRequest struct {
	Spirit *Spirit `protobuf:"bytes,1,opt,name=spirit" json:"spirit,omitempty"`
}

func (m *SpiritUpdateRequest) Reset()                    { *m = SpiritUpdateRequest{} }
func (m *SpiritUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*SpiritUpdateRequest) ProtoMessage()               {}
func (*SpiritUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SpiritUpdateRequest) GetSpirit() *Spirit {
	if m != nil {
		return m.Spirit
	}
	return nil
}

type SpiritDeleteRequest struct {
	Spirit *Spirit `protobuf:"bytes,1,opt,name=spirit" json:"spirit,omitempty"`
}

func (m *SpiritDeleteRequest) Reset()                    { *m = SpiritDeleteRequest{} }
func (m *SpiritDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*SpiritDeleteRequest) ProtoMessage()               {}
func (*SpiritDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SpiritDeleteRequest) GetSpirit() *Spirit {
	if m != nil {
		return m.Spirit
	}
	return nil
}

type SpiritSearchRequest struct {
	Spirit *Spirit `protobuf:"bytes,1,opt,name=spirit" json:"spirit,omitempty"`
}

func (m *SpiritSearchRequest) Reset()                    { *m = SpiritSearchRequest{} }
func (m *SpiritSearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SpiritSearchRequest) ProtoMessage()               {}
func (*SpiritSearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SpiritSearchRequest) GetSpirit() *Spirit {
	if m != nil {
		return m.Spirit
	}
	return nil
}

type SpiritCreationResponse struct {
	Spirit *Spirit `protobuf:"bytes,1,opt,name=spirit" json:"spirit,omitempty"`
}

func (m *SpiritCreationResponse) Reset()                    { *m = SpiritCreationResponse{} }
func (m *SpiritCreationResponse) String() string            { return proto.CompactTextString(m) }
func (*SpiritCreationResponse) ProtoMessage()               {}
func (*SpiritCreationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SpiritCreationResponse) GetSpirit() *Spirit {
	if m != nil {
		return m.Spirit
	}
	return nil
}

type SpiritUpdateResponse struct {
	Spirit *Spirit `protobuf:"bytes,1,opt,name=spirit" json:"spirit,omitempty"`
}

func (m *SpiritUpdateResponse) Reset()                    { *m = SpiritUpdateResponse{} }
func (m *SpiritUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*SpiritUpdateResponse) ProtoMessage()               {}
func (*SpiritUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SpiritUpdateResponse) GetSpirit() *Spirit {
	if m != nil {
		return m.Spirit
	}
	return nil
}

type SpiritDeleteResponse struct {
	Deleted bool `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *SpiritDeleteResponse) Reset()                    { *m = SpiritDeleteResponse{} }
func (m *SpiritDeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*SpiritDeleteResponse) ProtoMessage()               {}
func (*SpiritDeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SpiritDeleteResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type SpiritSearchResponse struct {
	Spirit []*Spirit `protobuf:"bytes,1,rep,name=spirit" json:"spirit,omitempty"`
}

func (m *SpiritSearchResponse) Reset()                    { *m = SpiritSearchResponse{} }
func (m *SpiritSearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SpiritSearchResponse) ProtoMessage()               {}
func (*SpiritSearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SpiritSearchResponse) GetSpirit() []*Spirit {
	if m != nil {
		return m.Spirit
	}
	return nil
}

func init() {
	proto.RegisterType((*Spirit)(nil), "gogrpc.Spirit")
	proto.RegisterType((*SpiritCreationRequest)(nil), "gogrpc.SpiritCreationRequest")
	proto.RegisterType((*SpiritUpdateRequest)(nil), "gogrpc.SpiritUpdateRequest")
	proto.RegisterType((*SpiritDeleteRequest)(nil), "gogrpc.SpiritDeleteRequest")
	proto.RegisterType((*SpiritSearchRequest)(nil), "gogrpc.SpiritSearchRequest")
	proto.RegisterType((*SpiritCreationResponse)(nil), "gogrpc.SpiritCreationResponse")
	proto.RegisterType((*SpiritUpdateResponse)(nil), "gogrpc.SpiritUpdateResponse")
	proto.RegisterType((*SpiritDeleteResponse)(nil), "gogrpc.SpiritDeleteResponse")
	proto.RegisterType((*SpiritSearchResponse)(nil), "gogrpc.SpiritSearchResponse")
	proto.RegisterEnum("gogrpc.Spirit_SpiritType", Spirit_SpiritType_name, Spirit_SpiritType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SpiritService service

type SpiritServiceClient interface {
	CreateSpirit(ctx context.Context, in *SpiritCreationRequest, opts ...grpc.CallOption) (*SpiritCreationResponse, error)
	UpdateSpirit(ctx context.Context, in *SpiritUpdateRequest, opts ...grpc.CallOption) (*SpiritUpdateResponse, error)
	DeleteSpirit(ctx context.Context, in *SpiritDeleteRequest, opts ...grpc.CallOption) (*SpiritDeleteResponse, error)
	SearchSpirit(ctx context.Context, in *SpiritSearchRequest, opts ...grpc.CallOption) (*SpiritSearchResponse, error)
}

type spiritServiceClient struct {
	cc *grpc.ClientConn
}

func NewSpiritServiceClient(cc *grpc.ClientConn) SpiritServiceClient {
	return &spiritServiceClient{cc}
}

func (c *spiritServiceClient) CreateSpirit(ctx context.Context, in *SpiritCreationRequest, opts ...grpc.CallOption) (*SpiritCreationResponse, error) {
	out := new(SpiritCreationResponse)
	err := grpc.Invoke(ctx, "/gogrpc.SpiritService/CreateSpirit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiritServiceClient) UpdateSpirit(ctx context.Context, in *SpiritUpdateRequest, opts ...grpc.CallOption) (*SpiritUpdateResponse, error) {
	out := new(SpiritUpdateResponse)
	err := grpc.Invoke(ctx, "/gogrpc.SpiritService/UpdateSpirit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiritServiceClient) DeleteSpirit(ctx context.Context, in *SpiritDeleteRequest, opts ...grpc.CallOption) (*SpiritDeleteResponse, error) {
	out := new(SpiritDeleteResponse)
	err := grpc.Invoke(ctx, "/gogrpc.SpiritService/DeleteSpirit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spiritServiceClient) SearchSpirit(ctx context.Context, in *SpiritSearchRequest, opts ...grpc.CallOption) (*SpiritSearchResponse, error) {
	out := new(SpiritSearchResponse)
	err := grpc.Invoke(ctx, "/gogrpc.SpiritService/SearchSpirit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SpiritService service

type SpiritServiceServer interface {
	CreateSpirit(context.Context, *SpiritCreationRequest) (*SpiritCreationResponse, error)
	UpdateSpirit(context.Context, *SpiritUpdateRequest) (*SpiritUpdateResponse, error)
	DeleteSpirit(context.Context, *SpiritDeleteRequest) (*SpiritDeleteResponse, error)
	SearchSpirit(context.Context, *SpiritSearchRequest) (*SpiritSearchResponse, error)
}

func RegisterSpiritServiceServer(s *grpc.Server, srv SpiritServiceServer) {
	s.RegisterService(&_SpiritService_serviceDesc, srv)
}

func _SpiritService_CreateSpirit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpiritCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiritServiceServer).CreateSpirit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gogrpc.SpiritService/CreateSpirit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiritServiceServer).CreateSpirit(ctx, req.(*SpiritCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiritService_UpdateSpirit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpiritUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiritServiceServer).UpdateSpirit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gogrpc.SpiritService/UpdateSpirit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiritServiceServer).UpdateSpirit(ctx, req.(*SpiritUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiritService_DeleteSpirit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpiritDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiritServiceServer).DeleteSpirit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gogrpc.SpiritService/DeleteSpirit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiritServiceServer).DeleteSpirit(ctx, req.(*SpiritDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpiritService_SearchSpirit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpiritSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiritServiceServer).SearchSpirit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gogrpc.SpiritService/SearchSpirit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiritServiceServer).SearchSpirit(ctx, req.(*SpiritSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpiritService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gogrpc.SpiritService",
	HandlerType: (*SpiritServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSpirit",
			Handler:    _SpiritService_CreateSpirit_Handler,
		},
		{
			MethodName: "UpdateSpirit",
			Handler:    _SpiritService_UpdateSpirit_Handler,
		},
		{
			MethodName: "DeleteSpirit",
			Handler:    _SpiritService_DeleteSpirit_Handler,
		},
		{
			MethodName: "SearchSpirit",
			Handler:    _SpiritService_SearchSpirit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spirits.proto",
}

func init() { proto.RegisterFile("spirits.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5f, 0x8f, 0xd2, 0x4e,
	0x14, 0xa5, 0x2d, 0x14, 0xb8, 0xfc, 0x49, 0x7f, 0xf7, 0xb7, 0x6e, 0xc6, 0x75, 0x35, 0x4d, 0x1f,
	0x0c, 0x2f, 0x12, 0x83, 0xcf, 0xfe, 0x03, 0x12, 0x1f, 0x4c, 0x34, 0x29, 0x1a, 0x13, 0xdf, 0x2a,
	0x5c, 0xcb, 0x44, 0xda, 0xa9, 0xd3, 0xc1, 0x84, 0x0f, 0xe6, 0x67, 0xf0, 0x6b, 0x99, 0xce, 0xb4,
	0x61, 0x87, 0xb0, 0x89, 0xab, 0x4f, 0xf4, 0xdc, 0xc3, 0x39, 0x77, 0xce, 0xed, 0xed, 0xc0, 0xa8,
	0x2c, 0xb8, 0xe4, 0xaa, 0x9c, 0x16, 0x52, 0x28, 0x81, 0x7e, 0x2a, 0x52, 0x59, 0xac, 0xa3, 0x9f,
	0x1e, 0xf8, 0x2b, 0xcd, 0xe0, 0x18, 0x5c, 0xbe, 0x61, 0x4e, 0xe8, 0x4c, 0xfa, 0xb1, 0xcb, 0x37,
	0x88, 0xd0, 0x7e, 0x97, 0x64, 0xc4, 0x5c, 0x5d, 0xd1, 0xcf, 0x78, 0x0d, 0xfd, 0x25, 0x2f, 0x15,
	0xdf, 0xed, 0x48, 0x32, 0x4f, 0x13, 0xc7, 0x02, 0x32, 0xe8, 0xce, 0x85, 0x52, 0x15, 0xd7, 0xd6,
	0x5c, 0x03, 0x2b, 0x66, 0x21, 0xf6, 0xb9, 0x92, 0x07, 0xd6, 0x31, 0x4c, 0x0d, 0xf1, 0x12, 0xfc,
	0x98, 0x52, 0x2e, 0x72, 0xe6, 0x6b, 0xa2, 0x46, 0x18, 0xc2, 0x60, 0x21, 0xb2, 0x42, 0x94, 0x5c,
	0x55, 0x64, 0x57, 0x93, 0x37, 0x4b, 0xf8, 0x04, 0xda, 0xea, 0x50, 0x10, 0xeb, 0x85, 0xce, 0x64,
	0x3c, 0xbb, 0x3f, 0x35, 0x89, 0xa6, 0x26, 0x4d, 0xfd, 0xf3, 0xe1, 0x50, 0x50, 0xac, 0xff, 0x86,
	0x01, 0x78, 0xaf, 0x53, 0x62, 0xfd, 0xd0, 0x99, 0x74, 0xe2, 0xea, 0x11, 0x23, 0x18, 0xea, 0xf3,
	0xf1, 0x3c, 0x5d, 0x26, 0x8a, 0x18, 0x84, 0xce, 0xc4, 0x8b, 0xad, 0x1a, 0x5e, 0x40, 0x67, 0xb5,
	0x16, 0x92, 0xd8, 0x20, 0x74, 0x26, 0x6e, 0x6c, 0x80, 0x89, 0x93, 0x65, 0x94, 0x2b, 0x36, 0x6c,
	0xe2, 0x68, 0x18, 0x7d, 0x05, 0x38, 0x76, 0xc6, 0x21, 0xf4, 0xf4, 0x09, 0xb6, 0xfb, 0x2c, 0x68,
	0x35, 0xe8, 0x13, 0xcf, 0x29, 0x70, 0x70, 0x0c, 0xa0, 0xd1, 0x96, 0x97, 0xdf, 0x0e, 0x81, 0x8b,
	0xff, 0xc1, 0xa8, 0xc2, 0x8b, 0x6d, 0x92, 0x15, 0x49, 0x9a, 0x53, 0xe0, 0xe1, 0x00, 0xba, 0x55,
	0xe9, 0x0d, 0xcf, 0x83, 0x76, 0xa3, 0x9e, 0x73, 0x92, 0x41, 0x27, 0x7a, 0x09, 0xf7, 0x4c, 0x9f,
	0x85, 0xa4, 0xa4, 0x1a, 0x47, 0x4c, 0xdf, 0xf7, 0x54, 0x2a, 0x7c, 0x0c, 0xbe, 0x79, 0xd3, 0xfa,
	0x4d, 0x0e, 0x66, 0x63, 0x7b, 0x2e, 0x71, 0xcd, 0x46, 0xcf, 0xe1, 0x7f, 0x53, 0xf9, 0x58, 0x6c,
	0x12, 0x45, 0x7f, 0x2d, 0x5f, 0xd2, 0x8e, 0xfe, 0x41, 0xbe, 0xa2, 0x44, 0xae, 0xb7, 0x77, 0x95,
	0xbf, 0x82, 0xcb, 0xd3, 0xf4, 0x65, 0x21, 0xf2, 0x92, 0xfe, 0xd8, 0xe1, 0x05, 0x5c, 0xd8, 0xf1,
	0xef, 0xa8, 0x7f, 0xda, 0xe8, 0x9b, 0xfc, 0xb5, 0x9e, 0x41, 0x77, 0xa3, 0x2b, 0xe6, 0x4b, 0xea,
	0xc5, 0x0d, 0x3c, 0x76, 0x6c, 0x22, 0x9f, 0xe9, 0xe8, 0xdd, 0xde, 0x71, 0xf6, 0xcb, 0x85, 0x51,
	0x63, 0x20, 0x7f, 0xf0, 0x35, 0xe1, 0x7b, 0x18, 0xea, 0xfc, 0x54, 0x7f, 0xc0, 0x0f, 0x6d, 0xe5,
	0xc9, 0x66, 0x5c, 0x3d, 0xba, 0x8d, 0x36, 0x07, 0x89, 0x5a, 0xf8, 0x16, 0x86, 0x66, 0x1c, 0xb5,
	0xe1, 0x03, 0x5b, 0x61, 0x6d, 0xca, 0xd5, 0xf5, 0x79, 0xf2, 0xa6, 0x99, 0x99, 0xcd, 0x79, 0x33,
	0x6b, 0x6f, 0x4e, 0xcd, 0xec, 0xa1, 0x1a, 0x33, 0x33, 0xb6, 0xf3, 0x66, 0xd6, 0x16, 0x9d, 0x9a,
	0xd9, 0xf3, 0x8e, 0x5a, 0xf3, 0xde, 0xe7, 0xfa, 0xf6, 0xfb, 0xe2, 0xeb, 0xcb, 0xf0, 0xd9, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0xb2, 0xe3, 0x97, 0x1d, 0x05, 0x00, 0x00,
}
